### ISSUE TITLE
(TRANSLATION) trzeba to przerobic zeby opisywalo takze zapki P2C (z profilu)

### ISSUE THREAD

**Issue by az** [eventjuicer/exhibitors#93]
![Uploading image.png…]()

**Comment by KarolinaTEH** [comment]
@az podeślesz please jeszcze raz screena? nie otwiera mi się plik 
![image](https://user-images.githubusercontent.com/80756258/213114772-2afa51c9-2c33-416d-ad08-7bb40550db5d.png)

**Comment by az** [comment]
![213015776-2e9cb50a-7de9-43c1-aab4-78f9a6304362](https://user-images.githubusercontent.com/2198/213144139-a6f06d0b-e848-4ba8-bf55-5c460f06b7bc.jpeg)

@KarolinaTEH here it is...czyli kejs jest taki...teraz to opowiada tylko o zapkach Cp2 (z listy visitorsow) a doszly te z profilu
