### ISSUE TITLE
(MAINTENANCE) add icons to staff

### ISSUE THREAD

**Issue by KarolinaTEH** [eventjuicer/exhibitors#95]
@az prośba o dodanie ikonek w https://staff.targiehandlu.pl/ do counter i default_furniture

lepszych propozycji nie znalazłam: 

import Crop32Icon from '@material-ui/icons/Crop32';

import DeckIcon from '@material-ui/icons/Deck';

https://v4.mui.com/components/material-icons/#material-icons

**Comment by KarolinaTEH** [comment]
@az display_75: import AddToQueueIcon from '@material-ui/icons/AddToQueue';

**Comment by az** [comment]
@KarolinaTEH display_75 zmienilam w adminie i localise (re: account) na **dis75play** ... bo tak dziala wyszykiwanie uslug w staff ze display (jako phrase) zawieral sie w display_75
